### ISSUE TITLE
Internal Server Error - Call to undefined function App\Http\Middleware\debug() - Error on all pages

### ISSUE THREAD

**Issue by osaeafari** [gillesashley/cws-backend#62]
<img width="1508" alt="Screenshot 2024-08-21 at 9 28 32 AM" src="https://github.com/user-attachments/assets/f78bde8c-74f3-4ccc-929d-9cc1df5c490f">

**Comment by asieduernest12** [comment]
Please run composer install if the issue is happening locally.
If it's on prod then open the issue
