### ISSUE TITLE
mobile app profile page 

### ISSUE THREAD

**Issue by osaeafari** [gillesashley/cws-backend#76]
The user profile data is not showing, but rather the old or preloaded data of #June Feil is showing. and even with that, the constituency, region and area is also not showing.

![WhatsApp Image 2024-09-02 at 11 44 16 (2)](https://github.com/user-attachments/assets/71a0bf35-c4e9-4388-a0b3-1d0016686cd1)

**Comment by asieduernest12** [comment]
fixed
